#!/bin/bash

cd /var/www/evolution/algorithm/musicians
/usr/local/perlgp-1.0.2/bin/perlgp-run.pl -loop &>/tmp/perlgp-musician.log &

cd /var/www/evolution/algorithm/nonmusicians
/usr/local/perlgp-1.0.2/bin/perlgp-run.pl -loop &>/tmp/perlgp-nonmusician.log &

